# Generated by Django 4.0.4 on 2022-06-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleanRobot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, 'Manual'), (2, 'Automatic'), (3, 'Error'), (4, 'Idle')])),
                ('velocity', models.FloatField(blank=True, null=True)),
                ('positionX', models.FloatField(blank=True, null=True)),
                ('positionY', models.FloatField(blank=True, null=True)),
                ('angleTHETA', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'CleanRobot',
                'verbose_name_plural': 'CleanRobots',
            },
        ),
    ]
